// AUTO-GENERATED by scripts/sync-deployments.ts — do not edit manually
// Run: npx tsx scripts/sync-deployments.ts

export interface DeployedContract {
  address: `0x${string}`;
}

export interface ChainDeployment {
  chainId: number;
  name: string;
  contracts: Partial<Record<'ABIDecoder' | 'BLSExposer' | 'BLSRegistry' | 'BlobAuthenticatedMessagingCore' | 'ECDSARegistry' | 'SignatureRegistryDispatcher' | 'SimpleBoolVerifier' | 'SocialBlobsCore', DeployedContract>>;
}

const DEPLOYMENTS: Record<number, ChainDeployment> = {
  11155111: {
    chainId: 11155111,
    name: 'sepolia',
    contracts: {
      SocialBlobsCore: { address: '0x11a825a0774d0471292eab4706743bffcdd5d137' },
      SimpleBoolVerifier: { address: '0xdec5faa3e32d6296e53bae7e359e059b58a482f4' },
      BLSRegistry: { address: '0x15866bf5a8724f2aa9fe75e262d8f00ba2818e25' },
      BLSExposer: { address: '0x443029b4b96fbf2d8feba77d828a394d19615a48' },
      BlobAuthenticatedMessagingCore: { address: '0x9C4b230066a6808D83F5FBa0c040E0Df2Fcc7314' },
      SignatureRegistryDispatcher: { address: '0x3431A94c9132b8a1b0c4aE8a80E7Ef0F0EC630Cf' },
      ECDSARegistry: { address: '0xF4Ce909305a112C2CBEC6b339a42f34bA8bf3381' },
      ABIDecoder: { address: '0x3a1bB111079cBaF4CAc320545Bfd1f6A92250425' },
    },
  },
};

/**
 * Get deployment addresses for a given chain.
 * @param chainId - The chain ID (e.g., 1 for mainnet, 11155111 for sepolia)
 * @returns The deployment info, or undefined if no deployment exists for that chain
 */
export function getDeployment(chainId: number): ChainDeployment | undefined {
  return DEPLOYMENTS[chainId];
}

/**
 * Get all known deployments.
 */
export function getAllDeployments(): ChainDeployment[] {
  return Object.values(DEPLOYMENTS);
}
