#!/usr/bin/env npx tsx
/**
 * Sync ABIs from Foundry build output into the SDK.
 *
 * Usage:
 *   cd packages/bam-contracts && forge build
 *   npx tsx scripts/sync-abis.ts
 *
 * Reads JSON artifacts from bam-contracts/out/ and writes a generated
 * TypeScript file to bam-sdk/src/contracts/abis.ts with typed ABI constants.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const contractsOut = join(root, 'packages', 'bam-contracts', 'out');
const outputFile = join(root, 'packages', 'bam-sdk', 'src', 'contracts', 'abis.ts');

/** Map of export name → Forge artifact path (relative to out/) */
const ABI_MAP: Record<string, string> = {
  SOCIAL_BLOBS_CORE_ABI: 'SocialBlobsCore.sol/SocialBlobsCore.json',
  BAM_CORE_ABI: 'BlobAuthenticatedMessagingCore.sol/BlobAuthenticatedMessagingCore.json',
  BAM_DECODER_ABI: 'ABIDecoder.sol/ABIDecoder.json',
  BLS_EXPOSER_ABI: 'BLSExposer.sol/BLSExposer.json',
  SIMPLE_BOOL_VERIFIER_ABI: 'SimpleBoolVerifier.sol/SimpleBoolVerifier.json',
  BLS_REGISTRY_ABI: 'BLSRegistry.sol/BLSRegistry.json',
};

function extractAbi(artifactPath: string): unknown[] {
  const raw = readFileSync(join(contractsOut, artifactPath), 'utf-8');
  const artifact = JSON.parse(raw) as { abi: unknown[] };
  return artifact.abi;
}

function main() {
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/sync-abis.ts — do not edit manually',
    '// Run: npx tsx scripts/sync-abis.ts',
    '',
  ];

  for (const [name, artifactPath] of Object.entries(ABI_MAP)) {
    const abi = extractAbi(artifactPath);
    lines.push(`export const ${name} = ${JSON.stringify(abi, null, 2)} as const;`);
    lines.push('');
  }

  writeFileSync(outputFile, lines.join('\n'));
  console.log(`Wrote ${Object.keys(ABI_MAP).length} ABIs to ${outputFile}`);
}

main();
