#!/usr/bin/env npx tsx
/**
 * Sync deployment addresses into the SDK.
 *
 * Usage:
 *   npx tsx scripts/sync-deployments.ts
 *
 * Reads all JSON files from bam-contracts/deployments/ and generates
 * a typed TypeScript module at bam-sdk/src/contracts/deployments.ts.
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const deploymentsDir = join(root, 'packages', 'bam-contracts', 'deployments');
const outputFile = join(root, 'packages', 'bam-sdk', 'src', 'contracts', 'deployments.ts');

interface DeploymentContract {
  address: string;
  deployBlock?: number;
}

interface Deployment {
  chainId: number;
  name: string;
  contracts: Record<string, DeploymentContract>;
}

function main() {
  const files = readdirSync(deploymentsDir).filter((f) => f.endsWith('.json'));

  if (files.length === 0) {
    console.error('No deployment files found in', deploymentsDir);
    process.exit(1);
  }

  const deployments: Deployment[] = [];

  for (const file of files) {
    const raw = readFileSync(join(deploymentsDir, file), 'utf-8');
    deployments.push(JSON.parse(raw) as Deployment);
  }

  // Sort by chain ID for deterministic output
  deployments.sort((a, b) => a.chainId - b.chainId);

  // Collect all contract names across all deployments for the type
  const allContractNames = new Set<string>();
  for (const d of deployments) {
    for (const name of Object.keys(d.contracts)) {
      allContractNames.add(name);
    }
  }
  const sortedNames = [...allContractNames].sort();

  const lines: string[] = [
    '// AUTO-GENERATED by scripts/sync-deployments.ts — do not edit manually',
    '// Run: npx tsx scripts/sync-deployments.ts',
    '',
    'export interface DeployedContract {',
    '  address: `0x${string}`;',
    '  /** Block number at which the contract was deployed. Optional. */',
    '  deployBlock?: number;',
    '}',
    '',
    'export interface ChainDeployment {',
    '  chainId: number;',
    '  name: string;',
    `  contracts: Partial<Record<${sortedNames.map((n) => `'${n}'`).join(' | ')}, DeployedContract>>;`,
    '}',
    '',
    'const DEPLOYMENTS: Record<number, ChainDeployment> = {',
  ];

  for (const d of deployments) {
    lines.push(`  ${d.chainId}: {`);
    lines.push(`    chainId: ${d.chainId},`);
    lines.push(`    name: '${d.name}',`);
    lines.push('    contracts: {');
    for (const [name, info] of Object.entries(d.contracts)) {
      const fields = [`address: '${info.address}'`];
      if (info.deployBlock !== undefined) {
        fields.push(`deployBlock: ${info.deployBlock}`);
      }
      lines.push(`      ${name}: { ${fields.join(', ')} },`);
    }
    lines.push('    },');
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');
  lines.push('/**');
  lines.push(' * Get deployment addresses for a given chain.');
  lines.push(' * @param chainId - The chain ID (e.g., 1 for mainnet, 11155111 for sepolia)');
  lines.push(' * @returns The deployment info, or undefined if no deployment exists for that chain');
  lines.push(' */');
  lines.push('export function getDeployment(chainId: number): ChainDeployment | undefined {');
  lines.push('  return DEPLOYMENTS[chainId];');
  lines.push('}');
  lines.push('');
  lines.push('/**');
  lines.push(' * Get all known deployments.');
  lines.push(' */');
  lines.push('export function getAllDeployments(): ChainDeployment[] {');
  lines.push('  return Object.values(DEPLOYMENTS);');
  lines.push('}');
  lines.push('');

  writeFileSync(outputFile, lines.join('\n'));
  console.log(`Wrote deployments for ${deployments.length} chain(s) to ${outputFile}`);
  for (const d of deployments) {
    console.log(`  ${d.name} (${d.chainId}): ${Object.keys(d.contracts).length} contracts`);
  }
}

main();
