import { describe, expect, it } from 'vitest';

import type { Address, BAMMessage } from '../../src/types.js';
import { decodeBatchABI, encodeBatchABI } from '../../src/codec/abi.js';
import { bytesToHex } from '../../src/message.js';

/**
 * Browser-runtime parity for the ABI codec.
 *
 * The ABI codec is pure CPU work (viem's `encodeAbiParameters` /
 * `decodeAbiParameters` plus a 65-byte sig split). It must produce
 * byte-identical output under jsdom and Node and round-trip identically
 * — there's no Node-only primitive in scope.
 */

function hex(n: number): string {
  return n.toString(16).padStart(2, '0');
}

function makeMessage(seed: number, contentsLen: number): BAMMessage {
  const sender = ('0x' + hex(seed).repeat(20)) as Address;
  const contents = new Uint8Array(contentsLen);
  for (let i = 0; i < contentsLen; i++) contents[i] = (seed + i) & 0xff;
  return { sender, nonce: BigInt(seed * 1000 + 1), contents };
}

function makeSig(seed: number): Uint8Array {
  const out = new Uint8Array(65);
  for (let i = 0; i < 65; i++) out[i] = (seed * 7 + i) & 0xff;
  return out;
}

describe('cross-runtime ABI codec parity (browser)', () => {
  it('jsdom environment is active (window is defined)', () => {
    // @ts-expect-error — window is provided by jsdom at runtime
    expect(typeof window).toBe('object');
  });

  it('encodes a single-message batch to a non-empty, word-aligned blob', () => {
    const msgs = [makeMessage(1, 40)];
    const sigs = [makeSig(1)];
    const encoded = encodeBatchABI(msgs, sigs);
    expect(encoded.length).toBeGreaterThan(0);
    expect(encoded.length % 32).toBe(0);
  });

  it('round-trips a multi-message batch under jsdom', () => {
    const msgs = [makeMessage(1, 40), makeMessage(2, 100), makeMessage(3, 7)];
    const sigs = [makeSig(1), makeSig(2), makeSig(3)];
    const decoded = decodeBatchABI(encodeBatchABI(msgs, sigs));
    expect(decoded.messages.length).toBe(3);
    for (let i = 0; i < 3; i++) {
      expect(decoded.messages[i].sender.toLowerCase()).toBe(msgs[i].sender);
      expect(decoded.messages[i].nonce).toBe(msgs[i].nonce);
      expect(Array.from(decoded.messages[i].contents)).toEqual(Array.from(msgs[i].contents));
      expect(Array.from(decoded.signatures[i])).toEqual(Array.from(sigs[i]));
    }
  });

  it('produces the byte-identical Node-locked vector under jsdom', () => {
    // Locked vector: hex of `encodeBatchABI([makeMessage(1, 40)], [makeSig(1)])`
    // produced under Node. If jsdom drifts from Node bytes, the runtimes
    // have diverged on viem's ABI marshalling — that's the regression we
    // want to surface.
    const msgs = [makeMessage(1, 40)];
    const sigs = [makeSig(1)];
    const encoded = encodeBatchABI(msgs, sigs);
    expect(bytesToHex(encoded)).toBe(NODE_REFERENCE);
  });
});

// Generated by running `encodeBatchABI([makeMessage(1, 40)], [makeSig(1)])`
// under Node and pasting the hex output. Any difference in byte layout
// between runtimes (viem drift, platform-specific BigInt serialisation)
// will fail this check.
const NODE_REFERENCE =
  '0x0000000000000000000000000000000000000000000000000000000000000040' +
  '0000000000000000000000000000000000000000000000000000000000000140' +
  '0000000000000000000000000000000000000000000000000000000000000001' +
  '0000000000000000000000000000000000000000000000000000000000000020' +
  '0000000000000000000000000101010101010101010101010101010101010101' +
  '00000000000000000000000000000000000000000000000000000000000003e9' +
  '0000000000000000000000000000000000000000000000000000000000000060' +
  '0000000000000000000000000000000000000000000000000000000000000028' +
  '0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20' +
  '2122232425262728000000000000000000000000000000000000000000000000' +
  '0000000000000000000000000000000000000000000000000000000000000041' +
  '0708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20212223242526' +
  '2728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40414243444546' +
  '4700000000000000000000000000000000000000000000000000000000000000';
